#!/bin/bash

#OktaAWSCLI
if [[ -d "$HOME/.okta_bw/bin" && ":$PATH:" != *":$HOME/.okta_bw/bin:"* ]]; then
    PATH="$HOME/.okta_bw/bin:$PATH"
fi

unset -f cfa
cfa () {
    open -a "Google Chrome Beta" https://bandwidth-jira.atlassian.net/browse/CFA-$1
}
export cfa

# AWS Profile setter. Uses AWS CLI to give you a select menu of profiles
unset -f awse
awse () {
    rm $HOME/.okta/cookies.properties
    echo ".okta/cookies cleaned up"

    profiles=`aws configure list-profiles`
    select option in $profiles; do
        echo "${cyan}Switching to AWS Profile: ${magenta}$option${default}"
        export AWS_PROFILE=$option
        break
    done
    # the <<- the dash makes it so the heredoc ignores the tabs
    withokta <<< "
1
2
"
}
export awse