#!/bin/bash

unset -f cfa
cfa () {
    open -a "Google Chrome" https://bandwidth-jira.atlassian.net/browse/CFA-$1
}
export cfa

# AWS Profile setter. Uses AWS CLI to give you a select menu of profiles
unset -f awse
awse () {
    profiles=`aws configure list-profiles`
    select option in $profiles; do
        echo "${cyan}Switching to AWS Profile: ${magenta}$option${default}"
        export AWS_PROFILE=$option
        break
    done
}
export awse