#!/usr/bin/env bash

# This git hook adds the branch name to the commit message.
# we are assuming your branch name is based on your jira ticket here.

# If a local prepare-commit-msg hook exists in the repo, delegate to it instead.
GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
LOCAL_HOOK="${GIT_DIR}/hooks/prepare-commit-msg"
THIS_HOOK=$(realpath "$0" 2>/dev/null || readlink -f "$0")

if [[ -f "$LOCAL_HOOK" && -x "$LOCAL_HOOK" ]]; then
  LOCAL_HOOK_REAL=$(realpath "$LOCAL_HOOK" 2>/dev/null || readlink -f "$LOCAL_HOOK")
  if [[ "$LOCAL_HOOK_REAL" != "$THIS_HOOK" ]]; then
    exec "$LOCAL_HOOK" "$@"
  fi
fi

# This way you can customize which branches should be skipped when
# prepending commit message.
echo "Preparing commit message..."
if [[ -z $BRANCHES_TO_SKIP ]]; then
  BRANCHES_TO_SKIP=(master main trunk dev develop development)
fi

BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_NAME="${BRANCH_NAME##*/}"

BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")
BRANCH_IN_COMMIT=$(grep -c "\[$BRANCH_NAME\]" $1)

if [[ -n $BRANCH_NAME && $BRANCH_EXCLUDED != 1 && $BRANCH_IN_COMMIT -lt 1 ]]; then
  sed -i.bak "1s/^/$BRANCH_NAME: /" $1
fi
