#!/bin/bash

green=$(tput setaf 2)
gold=$(tput setaf 3)
magenta=$(tput setaf 5)
cyan=$(tput setaf 6)
red=$(tput setaf 1)
default=$(tput sgr0)
gray=$(tput setaf 243)

info_box() {
  NUM=$((${#1} + 4))
  echo "${cyan}"

  # print the top of the info box
  eval printf %.0s# '{1..'"${NUM}"\}; echo

  # print the middle of the info box
  echo "# $1 #"

  # print the bottom of the info box
  eval printf %.0s# '{1..'"${NUM}"\}; echo

  echo "${default}"
}

BWUSERNAME=`whoami`

hash /opt/homebrew/bin/lpass 2>/dev/null || { echo -e "\n${red}LastPass-cli not found.\n${default}run '${cyan}brew install lastpass-cli${default}'"; kill -INT $$; }

info_box "Connecting to Bandwidth VPN"

STATE=`/opt/cisco/anyconnect/bin/vpn state | sed -n 7p | awk '{print $NF}'`

if [ -n "$1" ]; then
    /opt/cisco/anyconnect/bin/vpn $1
else
    if [ "$STATE" == "Connected" ]; then
        echo "already connected"
    else
        LPSTATUS=`lpass status`

        if [ "$LPSTATUS" == "Not logged in." ]; then
            read -p 'LastPass Email: ' LPEMAIL
            /opt/homebrew/bin/lpass login --trust $LPEMAIL
        fi

        LPPW=`lpass show --password bandwidth.com`

        # read -p 'MFA Code: ' MFA
        
        /opt/cisco/anyconnect/bin/vpn -s connect "RDU VPN" <<EOF
0
$BWUSERNAME
$LPPW
2
y
EOF
    fi
fi