#!/usr/bin/env bash
export CLICOLOR=1
export LSCOLORS=exFxcxdxbxegedabagacad
export ANSIBLE_NOCOWS=1
export HISTSIZE=5000

if [[ -f $HOME/.bashrc ]]; then
  source $HOME/.bashrc
fi

PATH=/usr/local/sbin:$PATH
PATH=/usr/local/bin:$PATH
PATH=/opt/homebrew/bin:$PATH # Silicon Macs
PATH="/opt/homebrew/opt/ruby/bin:$PATH" # Ruby installed with Homebrew
PATH="$(gem env home)/bin:$PATH" # gem install binaries
PATH="/usr/local/go/bin/:$PATH" # Go installed with its installer
PATH="$HOME/.volta/bin/":$PATH # volta global installs
PATH=$PATH:"$HOME/.rd/bin/" # Rancher Desktop binaries
PATH=$HOME/profile/bin:$PATH

export PATH=$PATH

#Editor config
EDITOR='vi'
export EDITOR
VISUAL='vi'
export VISUAL

export VIRTUAL_ENV_DISABLE_PROMPT=1

echo "Launching Starship"
eval "$(starship init bash)"


# Silence the bash deprecation message
export BASH_SILENCE_DEPRECATION_WARNING=1

export SCREENRC="$HOME/.screenrc"

# Homebrew Configuration
HOMEBREW_NO_AUTO_UPDATE=1

# K9S Path configuration
export K9S_CONFIG_DIR=$HOME/.config/k9s
# Required for K9S plugins to load in a directory
export XDG_DATA_HOME=$HOME/.config


# FZF configuration
[ -f $HOME/.fzf/.fzf.bash ] && source $HOME/.fzf/.fzf.bash

# FZF Git completions
source ~/profile/fzf-completions/git.sh